config/routes.rb
Rails.application.routes.draw do
  resources :features
  resources :events
  resources :services
  get 'services/index'

  get 'services/new'

  get 'services/edit'

  get 'services/delete'

  resources :meetings
  resources :locations
  resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

	has_many :links
	has_many :images
	has_many :videos

	include ActiveModel::Validations
	belongs_to :location, optional: true

	validates_presence_of :title, :synopsis, :content, :start, :endtime
	validates :title, length: { minimum: 2, maxiumum: 30 }
	validates :synopsis, length: { minimum: 2, maximum: 300 }
	validates :price, numericality: { only_float: true }
	validates_with EventValidator
	
	#scopes
	scope :chronological, -> { order(:start) }
	scope :soon, -> { where('start < ?', (Time.now + 3.weeks)) }
	scope :later, -> { where('start > ?', (Time.now + 3.weeks)) }
	
end

app/models/feature.rb
class Feature < ApplicationRecord
  include FeaturesHelper

  belongs_to :event, optional: true
  belongs_to :page, optional: true
  
  validates_presence_of :start, :endtime, :level
  
  validates_with FeatureValidator
  
  scope :pages, -> { where(:page_id.present?) }
  scope :events, -> { where(:event_id.present?) }
  scope :active, -> { where(:live => true) }
  scope :activated, -> { where('start <= ?', Time.now) }
  scope :not_expired, -> { where('endtime > ?', Time.now) }
  scope :prioritized, -> { order(level: :desc) }
  scope :for_page, -> { (page_id.present? && event_id.blank?) ? true : false }
  
  
  def for_page?
    (page_id.present? && event_id.blank?) ? true : false
  end
  
  def for_event?
    (page_id.blank? && event_id.present?) ? true : false
  end
  
  def for_youtube?
    self.class = Hash ? true : false
  end
  
end

app/models/location.rb
class Location < ApplicationRecord

	has_many :meetings
	
end

app/models/meeting.rb
class Meeting < ApplicationRecord

	belongs_to :location
	belongs_to :service, optional: true
	
	# Scopes based on meeting types
	scope :in_partial, -> { where(level: 1) }
	scope :ordered_by_day_and_time, -> { order(:weekday, :time) }
	scope :location, lambda { |location| where(:location_id => location) }
	scope :titled, lambda { |title| where(:title => title) }
	scope :on_day, lambda { |weekday| where(weekday: Date::DAYNAMES.index(weekday)) }
	

end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord

	has_many :meetings

	scope :ordered_by_priority, -> { order(priority: :asc) }

end

app/models/youtube.rb
class Youtube < ApplicationRecord

	require 'rss'


	
	def open_rss
		playlist_id = "PL6lGa-KrTKc1um2NJMFnXn_oFmzOe-oii"
		playlist_url = "https://www.youtube.com/feeds/videos.xml?playlist_id=" + playlist_id
		
		feed = Feedjira::Feed.fetch_and_parse playlist_url
		video = feed.entries.first
		
		details = {:title => video.title,
					:description => video.content,
					:url => video.media_url,
					:thumbnail => video.media_thumbnail_url
					}
		
		return details
	end

	def featured
		details = open_rss
		return details
	end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.all.order(:weekday).order(:time)
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:service_id, :level, :weekday, :time, :location_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/meetings/_form.html.erb
<%= form_for(meeting) do |f| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %>
    <%= f.select :location_id, $locations.collect { |location| [location.title, location.id] }, selected: meeting.location %>
  </div>
  
  <div class="field">
    <%= f.label :service %>
    <%= f.select :service_id,  $services.collect { |service| [service.title, service.id] }, selected: meeting.service_id %>
  </div>
  
  <div class="field">
    <%= f.label :weekday %>
    <%= f.select :weekday, [['Sunday', 0],
                           ['Monday', 1],
                           ['Tuesday', 2],
                           ['Wednesday', 3],
                           ['Thursday', 4],
                           ['Friday', 5],
                           ['Saturday', 6]] %>
  </div>
  
  <div class="field">
   <%= f.label :time %>
   <%= f.time_select :time, { minute_step: 5,
                              ampm: true } %>
  </div>

  <div class="field">
    <%= f.label :level, "Display in Locations Partial?" %>
    <%= f.radio_button :level, 1 %> Yes<br />
    <%= f.radio_button :level, 0 %> No
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<table>
  <thead>
    <tr>
      <th>Campus</th>
      <th>Title</th>
      <th>Weekday</th>
      <th>Time</th>
      <th>Display in Locations Partial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meetings.each do |meeting| %>
      <tr>
        <td><%= meeting.location.title.titlecase %></td>
        <td><%= meeting.service.title.titlecase %></td>
        <td><%= Date::DAYNAMES[meeting.weekday].titlecase %></td>
        <td><%= meeting.time.strftime("%I:%M %p") %></td>
        <td><%= meeting.level == 1 ? "Yes" : "No" %></td>
        <td><%= link_to 'Show', meeting %></td>
        <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
        <td><%= link_to 'Destroy', meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Campus:</strong>
  <%= @meeting.location.title.titlecase %>
</p>

<p>
  <strong>Title:</strong>
  <%= @meeting.service.title %>
</p>

<p>
  <strong>Weekday:</strong>
  <%= Date::DAYNAMES[@meeting.weekday] %>
</p>

<p>
  <strong>Time:</strong>
  <%= @meeting.time.strftime("%I:%M %p") %>
</p>

<p>
  <strong>Display in Locations Partial:</strong>
  <%= @meeting.level == 1 ? "Yes" : "No" %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>