config/routes.rb
Rails.application.routes.draw do
  resources :features
  resources :events
  resources :services
  get 'services/index'

  get 'services/new'

  get 'services/edit'

  get 'services/delete'

  resources :meetings
  resources :locations
  resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

	has_many :links
	has_many :images
	has_many :videos

	include ActiveModel::Validations
	belongs_to :location, optional: true

	validates_presence_of :title, :synopsis, :content, :start, :endtime
	validates :title, length: { minimum: 2, maxiumum: 30 }
	validates :synopsis, length: { minimum: 2, maximum: 300 }
	validates :price, numericality: { only_float: true }
	validates_with EventValidator
	
	#scopes
	scope :chronological, -> { order(:start) }
	scope :soon, -> { where('start < ?', (Time.now + 3.weeks)) }
	scope :later, -> { where('start > ?', (Time.now + 3.weeks)) }
	
end

app/models/feature.rb
class Feature < ApplicationRecord
  include FeaturesHelper

  belongs_to :event, optional: true
  belongs_to :page, optional: true
  
  validates_presence_of :start, :endtime, :level
  
  validates_with FeatureValidator
  
  scope :pages, -> { where(:page_id.present?) }
  scope :events, -> { where(:event_id.present?) }
  scope :active, -> { where(:live => true) }
  scope :activated, -> { where('start <= ?', Time.now) }
  scope :not_expired, -> { where('endtime > ?', Time.now) }
  scope :prioritized, -> { order(level: :desc) }
  scope :for_page, -> { (page_id.present? && event_id.blank?) ? true : false }
  
  
  def for_page?
    (page_id.present? && event_id.blank?) ? true : false
  end
  
  def for_event?
    (page_id.blank? && event_id.present?) ? true : false
  end
  
  def for_youtube?
    self.class = Hash ? true : false
  end
  
end

app/models/location.rb
class Location < ApplicationRecord

	has_many :meetings
	
end

app/models/meeting.rb
class Meeting < ApplicationRecord

	belongs_to :location
	belongs_to :service, optional: true
	
	# Scopes based on meeting types
	scope :in_partial, -> { where(level: 1) }
	scope :ordered_by_day_and_time, -> { order(:weekday, :time) }
	scope :location, lambda { |location| where(:location_id => location) }
	scope :titled, lambda { |title| where(:title => title) }
	scope :on_day, lambda { |weekday| where(weekday: Date::DAYNAMES.index(weekday)) }
	

end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord

	has_many :meetings

	scope :ordered_by_priority, -> { order(priority: :asc) }

end

app/models/youtube.rb
class Youtube < ApplicationRecord

	require 'rss'


	
	def open_rss
		playlist_id = "PL6lGa-KrTKc1um2NJMFnXn_oFmzOe-oii"
		playlist_url = "https://www.youtube.com/feeds/videos.xml?playlist_id=" + playlist_id
		
		feed = Feedjira::Feed.fetch_and_parse playlist_url
		video = feed.entries.first
		
		details = {:title => video.title,
					:description => video.content,
					:url => video.media_url,
					:thumbnail => video.media_thumbnail_url
					}
		
		return details
	end

	def featured
		details = open_rss
		return details
	end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :subtitle, :synopsis, :content, :location_id, :location_building, :location_address, :location_address2, :location_city, :location_state, :location_zip, :location_googlemapsid, :start, :endtime, :videos, :images, :links, :price)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/events/_form.html.erb
<%= form_for(event) do |f| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>

  <div class="field">
    <%= f.label :synopsis %>
    <%= f.text_area :synopsis %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.select :location_id, @locations.collect { |campus| [campus.title, campus.id] },
                                selected: event.location_id,
                                include_blank: true %>
    <br />- OR -<br />
    <%= f.label :location_building %>
    <%= f.text_field :location_building %>

    <div class="field">
      <%= f.label :location_address %>
      <%= f.text_field :location_address %>
    </div>

    <div class="field">
      <%= f.label :location_address2 %>
      <%= f.text_field :location_address2 %>
    </div>

    <div class="field">
      <%= f.label :location_city %>
      <%= f.text_field :location_city %>
    </div>

    <div class="field">
      <%= f.label :location_state %>
      <%= f.text_field :location_state %>
    </div>

    <div class="field">
      <%= f.label :location_zip %>
      <%= f.text_field :location_zip %>
    </div>

    <div class="field">
      <%= f.label :location_Google_Maps_Place_ID %>
      <%= f.text_field :location_googlemapsid %>
    </div>
  </div>

  <div class="field">
    <%= f.label :start %>
    <%= f.datetime_select :start, :order => [:month, :day, :year],
                                  :startyear => Date.today.year,
                                  :startmonth => Date.today.month,
                                  :startday => Date.today.day,
                                  :starthour => Time.now.hour,
                                  :default => 7.days.from_now,
                                  :minute_step => 5,
                                  :ampm => true,
                                  :use_short_month => true
                                  %>
  </div>

  <div class="field">
    <%= f.label :end, :title => "If no End date/time, make same as Start date/time." %>
    <%= f.datetime_select :endtime, :order => [:month, :day, :year],
                                :startyear => Date.today.year,
                                :startmonth => Date.today.month,
                                :startday => Date.today.day,
                                :starthour => Time.now.hour,
                                :default => 7.days.from_now + 2.hours,
                                :minute_step => 5,
                                :ampm => true,
                                :use_short_month => true
                                %>
  </div>

  <div class="field">
    <%= f.label :videos %>
    <%= f.text_field :videos_id, disabled: true %>
  </div>

  <div class="field">
    <%= f.label :images %>
    <%= f.text_field :images_id, disabled: true %>
  </div>

  <div class="field">
    <%= f.label :links %>
    <%= f.text_field :links_id, disabled: true %>
  </div>

  <div class="field">
    <%= f.label :price %>
    $<%= f.text_field :price, placeholder: "15.00" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<div>
    <% @events.each do |event| %>
      <div>
        <h2><%= event.title %></h2>
        <% if event.subtitle %>
          <i><%= event.subtitle %></i>
        <% end %>
        <p><i><%= event.synopsis %></i></p>
        <p><%= event.content %></p>
        <h4>Location</h4>
        <% if event.location_id %>
          <%= link_to event.location.title, location_path(event.location_id) %>
        <% else %>
        <%= link_to (URI.encode("https://www.google.com/maps/search/?api=1&query=" + event.location_address + " " + event.location_address2 + " " + event.location_city.titlecase + ", " + event.location_state.upcase + " " + event.location_zip + "&query_place_id=" + event.location_googlemapsid)) do %>
          <b><%= event.location_building %></b><br />
          <%= event.location_address %><br />
          <% unless event.location_address2.blank? %>
            <%= event.location_address2 %><br />
          <% end %>
          <%= event.location_city %>, <%= event.location_state %> <%= event.location_zip %><br />
        <% end %>
        <% end %>
        <br /><br />
        
        <strong>When:</strong>
        <%= event.start.strftime("%e %b %Y %H:%M%p") %>
        <% if event.start != event.endtime && event.start.day == event.endtime.day %>
        - <%= event.endtime.strftime("%H:%M%p") %>
        <% elsif event.start != event.endtime && event.start.day != event.endtime.day %>
        - <%= event.endtime.strftime("%e %b %Y %H:%M%p") %>
        <% end %>
        <br /><br />
        
        <% if event.price > 0 %>
          <b>Cost:</b> <%= event.price %>/person
        <% end %>
        
        <%= link_to 'Show', event %>
        <%= link_to 'Edit', edit_event_path(event) %>
        <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @event.subtitle %>
</p>

<p>
  <strong>Synopsis:</strong>
  <%= @event.synopsis %>
</p>

<p>
  <strong>Content:</strong>
  <%= simple_format(@event.content) %>
</p>

<p>
  <strong>Location:</strong>
  <% if @event.location_id %>
    <%= @event.location.title %>
  <% end %>
</p>

<p>
  <strong>Location building:</strong>
  <%= @event.location_building %>
</p>

<p>
  <strong>Location address:</strong>
  <%= @event.location_address %>
</p>

<p>
  <strong>Location address2:</strong>
  <%= @event.location_address2 %>
</p>

<p>
  <strong>Location city:</strong>
  <%= @event.location_city %>
</p>

<p>
  <strong>Location state:</strong>
  <%= @event.location_state %>
</p>

<p>
  <strong>Location zip:</strong>
  <%= @event.location_zip %>
</p>

<p>
  <strong>Location googlemapsid:</strong>
  <%= @event.location_googlemapsid %>
</p>

<p>
  <strong>Time:</strong>
  <%= @event.start.strftime("%e %b %Y %H:%M%p") %>
  <% if @event.start != @event.endtime && @event.start.day == @event.endtime.day %>
  - <%= @event.endtime.strftime("%H:%M%p") %>
  <% elsif @event.start != @event.endtime && @event.start.day != @event.endtime.day %>
  - <%= @event.endtime.strftime("%e %b %Y %H:%M%p") %>
  <% end %>
</p>

<p>
  <strong>Videos:</strong>
  <%= @event.videos_id %>
</p>

<p>
  <strong>Images:</strong>
  <%= @event.images_id %>
</p>

<p>
  <strong>Links:</strong>
  <%= @event.links_id %>
</p>

<% if @event.price > 0 %>
<p>
  <strong>Price:</strong>
  <%= number_to_currency(@event.price, unit: "$") %>
</p>

<% end %>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>