config/routes.rb
Rails.application.routes.draw do
  resources :features
  resources :events
  resources :services
  get 'services/index'

  get 'services/new'

  get 'services/edit'

  get 'services/delete'

  resources :meetings
  resources :locations
  resources :pages
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'pages#index'
end

app/models/event.rb
class Event < ApplicationRecord

	has_many :links
	has_many :images
	has_many :videos

	include ActiveModel::Validations
	belongs_to :location, optional: true

	validates_presence_of :title, :synopsis, :content, :start, :endtime
	validates :title, length: { minimum: 2, maxiumum: 30 }
	validates :synopsis, length: { minimum: 2, maximum: 300 }
	validates :price, numericality: { only_float: true }
	validates_with EventValidator
	
	#scopes
	scope :chronological, -> { order(:start) }
	scope :soon, -> { where('start < ?', (Time.now + 3.weeks)) }
	scope :later, -> { where('start > ?', (Time.now + 3.weeks)) }
	
end

app/models/feature.rb
class Feature < ApplicationRecord
  include FeaturesHelper

  belongs_to :event, optional: true
  belongs_to :page, optional: true
  
  validates_presence_of :start, :endtime, :level
  
  validates_with FeatureValidator
  
  scope :pages, -> { where(:page_id.present?) }
  scope :events, -> { where(:event_id.present?) }
  scope :active, -> { where(:live => true) }
  scope :activated, -> { where('start <= ?', Time.now) }
  scope :not_expired, -> { where('endtime > ?', Time.now) }
  scope :prioritized, -> { order(level: :desc) }
  scope :for_page, -> { (page_id.present? && event_id.blank?) ? true : false }
  
  
  def for_page?
    (page_id.present? && event_id.blank?) ? true : false
  end
  
  def for_event?
    (page_id.blank? && event_id.present?) ? true : false
  end
  
  def for_youtube?
    self.class = Hash ? true : false
  end
  
end

app/models/location.rb
class Location < ApplicationRecord

	has_many :meetings
	
end

app/models/meeting.rb
class Meeting < ApplicationRecord

	belongs_to :location
	belongs_to :service, optional: true
	
	# Scopes based on meeting types
	scope :in_partial, -> { where(level: 1) }
	scope :ordered_by_day_and_time, -> { order(:weekday, :time) }
	scope :location, lambda { |location| where(:location_id => location) }
	scope :titled, lambda { |title| where(:title => title) }
	scope :on_day, lambda { |weekday| where(weekday: Date::DAYNAMES.index(weekday)) }
	

end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord

	has_many :meetings

	scope :ordered_by_priority, -> { order(priority: :asc) }

end

app/models/youtube.rb
class Youtube < ApplicationRecord

	require 'rss'


	
	def open_rss
		playlist_id = "PL6lGa-KrTKc1um2NJMFnXn_oFmzOe-oii"
		playlist_url = "https://www.youtube.com/feeds/videos.xml?playlist_id=" + playlist_id
		
		feed = Feedjira::Feed.fetch_and_parse playlist_url
		video = feed.entries.first
		
		details = {:title => video.title,
					:description => video.content,
					:url => video.media_url,
					:thumbnail => video.media_thumbnail_url
					}
		
		return details
	end

	def featured
		details = open_rss
		return details
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include ApplicationHelper
  include IntelligentFeature
  require 'uri'
  
  before_action :set_globals



  private
  
  def set_globals
    @locations = Location.all
    @meetings = Meeting.all
    @services = Service.all
    @events = Event.all
    @pages = Page.all
    @top_features = featured
    
    @sorted_meetings = Meeting.in_partial.ordered_by_day_and_time.preload(:location, :service).group_by{|meeting| [meeting.service]}
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

	def meetings_grouped_by_weekday(meetings)
		# Receives array of meetings and outputs array of strings in format of "WKDY TIME, TIME and TIME"
		
		formatted_meetings = []
		
		meetings.each do |meeting|
			day = Regexp.new Date::ABBR_DAYNAMES[meeting.weekday]
			
			if formatted_meetings.any? { |val| day =~ val } == false
				# If weekday is not already listed in formatted_meetings, add a string in the format of "WKDY TIME" to the array
				formatted_meetings << "#{Date::ABBR_DAYNAMES[meeting.weekday]} #{meeting.time.strftime("%-l:%M %p")}"
			else
				s = formatted_meetings.find_index{ |d| d.include? Date::ABBR_DAYNAMES[meeting.weekday]}
				if formatted_meetings[s].include? "and"
					# If weekday is listed and already has an "and" (signifying multiple times in string), swap out all "and"s for commas and append "and TIME"
					statement = formatted_meetings[s]
					statement.gsub!(" and", ",")
					statement += " and #{meeting.time.strftime("%-l:%M %p")}"
					formatted_meetings[s] = statement
				else
					# If weekday is listed but with only one time, append "and TIME"
					formatted_meetings[s] = "#{formatted_meetings[s]} and #{meeting.time.strftime("%-l:%M %p")}"
				end
			end
		end
		return formatted_meetings
	end
	
	
	
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper

end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/application/_events.erb
<ul>
  <% @events.chronological.each do |e| %>
    <%= link_to event_path(e.id) do %>
      <div>
      <% if false %><%= e.image_ids %><% end %>
      <h2><%= e.title %></h2>
      <i><% if e.start.day != e.endtime.day %>
        <%= e.start.strftime("%a, %b %d") %> - <%= e.endtime.strftime("%a, %b %d") %>
      <% else %>
        <%= e.start.strftime("%a, %b %d at %-l:%M %p") %>
      <% end %></i>
        <p><%= e.synopsis %></p>
      </div>
    <% end %>
  <% end %>
</ul>

app/views/application/_features.erb
<ul>
    <% @top_features.each do |f| %>
        <% if f.class == Feature && f.event_id.present? && f.page_id.blank? %>
            <%= link_to event_path(f.event_id) do %>
                    <h2><%= f.event.title %></h2>
                    <i><% if f.event.start.day != f.event.endtime.day %>
                        <%= f.event.start.strftime("%a, %b %d") %> - <%= f.event.endtime.strftime("%a, %b %d") %>
                    <% else %>
                        <%= f.event.start.strftime("%a, %b %d at %-l:%M %p") %>
                    <% end %></i>
                    <p><%= f.caption.blank? ? f.event.synopsis : f.caption %></p>
                </div>
            <% end %>
        <% elsif f.class == Event %>
            <%= link_to event_path(f.id) do %>
                <div>
                    <h2><%= f.title %></h2>
                    <i><% if f.start.day != f.endtime.day %>
                        <%= f.start.strftime("%a, %b %d") %> - <%= f.endtime.strftime("%a, %b %d") %>
                    <% else %>
                        <%= f.start.strftime("%a, %b %d at %-l:%M %p") %>
                    <% end %></i>
                    <p><%= f.synopsis %></p>
                </div>
            <% end %>
        <% end %>
    <% end %>
</ul>


<% if false %>
<% if f.page %>
    <%= link_to page_path(f.page_id) do %>
        <div>
            <% if false %><%= f.page.image_id %><% end %>
            <h2><%= f.page.title %></h2>
            <p><%= f.caption %></p>
        </div>
    <% end %>
<% elsif f.event %>
    
    

<% elsif f.for_youtube? %>
    <%= link_to f[:url] do %>
        <div>
            <%= img_tag(f[:thumbnail]) %><% end %>
            <h2><%= f[:title] %></h2>
            <p><%= f[:caption] %></p>
        </div>
    <% end %>
<% end %>

app/views/application/_footer.html.erb
<ul>
  <li><ul>
    <li><h3>About</h3></li>
    <li>Beliefs</li>
    <li>Values</li>
    <li>Leadership</li>
  </ul></li>
  <li><ul>
    <li><h3>Media</h3></li>
    <li><%= link_to "Messages", "http://www.youtube.com/vc2online" %></li>
    <li><%= link_to "Worship", "https://itunes.apple.com/us/artist/vc2-music/1066077548" %></li>
  </ul></li>
  <li><ul>
    <li><h3>Ministries</h3></li>
    <li><%= link_to "Grow Groups", "https://vc2.churchcenter.com/groups/grow-groups" %></li>
    <li>Dream Teams</li>
    <li>VC3 - Kids</li>
    <li>Momentum Youth</li>
    <li>Bless The City</li>
  </ul></li>
  <li><ul>
    <li><h3>More</h3></li>
    <li><%= link_to "Events", events_path %></li>
    <li>Contact</li>
  </ul></li>
</ul>

<div>&copy;2017-<%= Time.now.year %> Victory Central Church. All rights reserved. | <%= link_to "Privacy Policy" %>

app/views/application/_locations.erb
<h1>This Weekend</h1>
<ul>
  <% @locations.each do |l| %>
    <div>
    <h2><%= l.title %></h2>
    <% if l.building != "" %><%= l.building.titlecase %><br /><% end %>
      <%= link_to (URI.encode("https://www.google.com/maps/search/?api=1&query=" + l.address + " " + l.address2 + " " + l.city.titlecase + ", " + l.state.upcase + " " + l.zip + "&query_place_id=" + l.googlemapsid)) do %>
        <%= l.address.titlecase %><br />
          <% if l.address2 != "" %><%= l.address2 %><br /><% end %>
          <%= l.city.titlecase + ", " + l.state.upcase + " " + l.zip %><br />
    <% end %>
    </div>
    <div>


      <% @sorted_meetings.each do |service| %>
        <h3><% thisservice = service[0][0] %><%= thisservice.title %></h3>
        <% thisservicemeetings = service[1] %>
        <% meetings_grouped_by_weekday(thisservicemeetings).each do |s| %>
          <%= s %><br />
        <% end %>
      <% end %>

  
    </div>
  <% end %>
</ul>

app/views/application/_nav.html.erb
<header>
  <span id="logo">VC2</span>
  <button id="navbutton">Menu</button>
</header>


<!-- NAVIGATION MENU -->


<nav id="navmenu">
  <ul>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Watch Online", "http://www.youtube.com/vc2online" %></li>
    <li><%= link_to "About", "http://www.vc2online.com/imnew.html" %></li>
    <li><%= link_to "Contact", "http://www.facebook.com/vc2online" %></li>
    <li><%= link_to "Resources", "http://www.facebook.com/vc2online" %></li>
    <li><%= link_to "Give", "http://give.vc2online.com" %></li>
  </ul>
</nav>